# Standards: 0.11
---

- import_tasks: "level-1/1.1.1.1.yml"
  when: "'1.1.1.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.2.yml"
  when: "'1.1.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.3.yml"
  when: "'1.1.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.4.yml"
  when: "'1.1.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.5.yml"
  when: "'1.1.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.2.yml"
  when: "'1.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.3.yml"
  when: "'1.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.4.yml"
  when: "'1.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.5.yml"
  when: "'1.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.8.yml"
  when: "'1.1.8' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.9.yml"
  when: "'1.1.9' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.10.yml"
  when: "'1.1.10' not in cis_level_1_exclusions"