# Standards: 0.11
---

- import_tasks: "level-1/1.1.1.1.yml"
  when: "'1.1.1.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.2.yml"
  when: "'1.1.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.3.yml"
  when: "'1.1.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.4.yml"
  when: "'1.1.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.1.5.yml"
  when: "'1.1.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.2.yml"
  when: "'1.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.3.yml"
  when: "'1.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.4.yml"
  when: "'1.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.5.yml"
  when: "'1.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.8.yml"
  when: "'1.1.8' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.9.yml"
  when: "'1.1.9' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.10.yml"
  when: "'1.1.10' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.14.yml"
  when: "'1.1.14' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.15.yml"
  when: "'1.1.15' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.16.yml"
  when: "'1.1.16' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.17.yml"
  when: "'1.1.17' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.18.yml"
  when: "'1.1.18' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.1.19.yml"
  when: "'1.1.19' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.2.1.yml"
  when: "'1.2.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.2.2.yml"
  when: "'1.2.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.2.3.yml"
  when: "'1.2.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.3.1.yml"
  when: "'1.3.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.3.2.yml"
  when: "'1.3.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.4.1.yml"
  when: "'1.4.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.4.2.yml"
  when: "'1.4.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.5.1.yml"
  when: "'1.5.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.5.2.yml"
  when: "'1.5.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.5.3.yml"
  when: "'1.5.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.1.yml"
  when: "'1.7.1.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.2.yml"
  when: "'1.7.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.3.yml"
  when: "'1.7.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.4.yml"
  when: "'1.7.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.5.yml"
  when: "'1.7.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.7.1.6.yml"
  when: "'1.7.1.6' not in cis_level_1_exclusions"
- import_tasks: "level-1/1.8.yml"
  when: "'1.8' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.1.1.yml"
  when: "'2.1.1.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.1.3.yml"
  when: "'2.1.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.2.yml"
  when: "'2.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.3.yml"
  when: "'2.1.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.4.yml"
  when: "'2.1.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.5.yml"
  when: "'2.1.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.6.yml"
  when: "'2.1.6' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.7.yml"
  when: "'2.1.7' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.8.yml"
  when: "'2.1.8' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.9.yml"
  when: "'2.1.9' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.10.yml"
  when: "'2.1.10' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.11.yml"
  when: "'2.1.11' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.12.yml"
  when: "'2.1.12' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.13.yml"
  when: "'2.1.13' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.14.yml"
  when: "'2.1.14' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.15.yml"
  when: "'2.1.15' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.16.yml"
  when: "'2.1.16' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.17.yml"
  when: "'2.1.17' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.18.yml"
  when: "'2.1.18' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.19.yml"
  when: "'2.1.19' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.20.yml"
  when: "'2.1.20' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.1.21.yml"
  when: "'2.1.21' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.2.1.yml"
  when: "'2.2.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.2.2.yml"
  when: "'2.2.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.2.3.yml"
  when: "'2.2.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.2.4.yml"
  when: "'2.2.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/2.2.5.yml"
  when: "'2.2.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.1.1.yml"
  when: "'3.1.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.1.2.yml"
  when: "'3.1.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.1.yml"
  when: "'3.2.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.2.yml"
  when: "'3.2.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.3.yml"
  when: "'3.2.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.4.yml"
  when: "'3.2.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.5.yml"
  when: "'3.2.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.6.yml"
  when: "'3.2.6' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.7.yml"
  when: "'3.2.7' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.8.yml"
  when: "'3.2.8' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.2.9.yml"
  when: "'3.2.9' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.3.1.yml"
  when: "'3.3.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.3.2.yml"
  when: "'3.3.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.3.3.yml"
  when: "'3.3.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.3.4.yml"
  when: "'3.3.4' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.3.5.yml"
  when: "'3.3.5' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.4.1.yml"
  when: "'3.4.1' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.4.2.yml"
  when: "'3.4.2' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.4.3.yml"
  when: "'3.4.3' not in cis_level_1_exclusions"
- import_tasks: "level-1/3.4.4.yml"
  when: "'3.4.4' not in cis_level_1_exclusions"