# Standards: 0.11
---

# 4.1.18 Ensure the audit configuration is immutable (Scored)

- name: 4.1.18 Ensure the audit configuration is immutable (Scored)
  shell: grep "^\s*[^#]" {{ cis_audit_rules_filename }} | tail -1
