# Standards: 0.11
---

# 1.1.19 - Disable Automounting

- name: 1.1.19 - Disable autofs
    debug: msg="*** autofs is not available on Amazon Linux 2."
    tags:
    - level-1
    - "1.1.19"
    - scored